

<MainScreen>:
    MDTopAppBar:
        pos_hint: {"top":1}
        title: "Calculator App"
    MDGridLayout:
        pos_hint: {"top":0.9}
        cols: 3
        spacing: dp(11)
        padding: dp(11)
        MenuButton:
            icon: "calculator-variant-outline"
            text: "Calculator"
        MenuButton:
            icon: "math-log"
            text: "Scientific Calculator"
        MenuButton:
            icon: "math-integral"
            text: "Calculus"
        MenuButton:
            icon: "cog"
            text: "Settings"
    