<MainScreen>:
    MDBoxLayout:
        orientation: "vertical"
        spacing: dp(15)
        
        MDTopAppBar:
            title: "Calculator App"
            elevation: 2

        MDGridLayout:
            cols: 3
            spacing: dp(12)
            padding: dp(12)

            MenuButton:
                icon: "calculator-variant-outline"
                text: "Calculator"

            MenuButton:
                icon: "math-log"
                text: "Scientific Calculator"

            MenuButton:
                icon: "math-integral"
                text: "Calculus"

            MenuButton:
                icon: "cog"
                text: "Settings"