<MainScreen>:
    
    MDBoxLayout:
        orientation: "vertical"
        spacing: dp(15)
        md_bg_color: app.theme_manager.theme_style["bg_color"]
        MDTopAppBar:
            title: "Calculator App"
            elevation: 2
            right_action_items: [["cog", lambda x: setattr(app.root, "current", "settings_screen")]]

        MDGridLayout:
            cols: 3
            spacing: dp(12)
            padding: dp(12)

            MenuButton:
                icon: "calculator-variant-outline"
                text: "Calculator"
                on_press: setattr(app.root, "current", "calculator_screen")

            MenuButton:
                icon: "math-log"
                text: "Scientific Calculator"
                on_press: setattr(app.root, "current", "scientific_screen")

            MenuButton:
                icon: "math-integral"
                text: "Calculus"
                on_press: setattr(app.root, "current", "calculus_screen")
            MenuButton:
                icon: "numeric"
                text: "GCF & LCM"
                on_press: setattr(app.root, "current", "gcf_lcm_screen")
                
            MenuButton:
                icon: "diamond-stone"
                text: "Prime Checker"
                on_press: setattr(app.root, "current", "prime_checker_screen")

            MenuButton:
                icon: "cached"
                text: "Unit Converter"
                
            MenuButton:
                icon: "scale-bathroom"
                text: "BMI"
                
            MenuButton:
                icon: "cake-variant"
                text: "Age Calculator"
                
            MenuButton:
                icon: "timer-outline"
                text: "Time Interval"