#: include ui/KVs/main_screen.kv
#: include ui/KVs/calculator_screen.kv
#: include ui/KVs/scientific_screen.kv
#: include ui/KVs/calculus_screen.kv
#: include ui/KVs/settings_screen.kv
#: include ui/KVs/gcf_lcm_screen.kv
#: include ui/KVs/prime_checker_screen.kv

#: import MainScreen ui.main_screen
#: import CalculatorScreen ui.calculator_screen
#: import ScientificScreen ui.scientific_screen
#: import CalculusScreen ui.calculus_screen
#: import SettingsScreen ui.settings_screen
#: import GCFLCMScreen ui.gcf_lcm_screen
#: import PrimeCheckerScreen ui.prime_checker_screen

MDScreenManager:
    
    MainScreen:
        name: "main_screen"
        
    CalculatorScreen:
        name: "calculator_screen"
        
    ScientificScreen:
        name: "scientific_screen"
        
    CalculusScreen:
        name: "calculus_screen"
        
    SettingsScreen:
        name: "settings_screen"
    
    GCFLCMScreen:
        name: "gcf_lcm_screen"
        
    PrimeCheckerScreen:
        name: "prime_checker_screen"