#: include ui/KVs/main_screen.kv
#: include ui/KVs/calculator_screen.kv
#: include ui/KVs/scientific_screen.kv

#: import MainScreen ui.main_screen
#: import CalculatorScreen ui.calculator_screen
#: import ScientificScreen ui.scientific_screen

MDScreenManager:
    
    MainScreen:
        name: "main_screen"
        
    CalculatorScreen:
        name: "calculator_screen"
        
    ScientificScreen:
        name: "scientific_screen"