#: include ui/KVs/main_screen.kv
#: include ui/KVs/calculator_screen.kv
#: include ui/KVs/scientific_screen.kv
#: include ui/KVs/calculus_screen.kv
#: include ui/KVs/settings_screen.kv

#: import MainScreen ui.main_screen
#: import CalculatorScreen ui.calculator_screen
#: import ScientificScreen ui.scientific_screen
#: import CalculusScreen ui.calculus_screen
#: import SettingsScreen ui.settings_screen

MDScreenManager:
    
    MainScreen:
        name: "main_screen"
        
    CalculatorScreen:
        name: "calculator_screen"
        
    ScientificScreen:
        name: "scientific_screen"
        
    CalculusScreen:
        name: "calculus_screen"
        
    SettingsScreen:
        name: "settings_screen"